spring:
     datasource:
       url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
       username: root
       password: SK0143@kumar


       #JPA SETTINGS PROPERTIES..
     jpa.hibernate.ddl_auto: create
